import org.jetbrains.kotlin.gradle.dsl.JvmTarget
import org.jetbrains.kotlin.gradle.tasks.KotlinCompile

plugins {
    id("com.android.library")
    id("com.google.protobuf")
    kotlin("multiplatform")
    id("com.google.devtools.ksp")
    `maven-publish`
}

group = "org.matilda"
version = providers.gradleProperty("VERSION").get()

repositories {
    mavenCentral()
    google()
    mavenLocal()
}

java {
    sourceCompatibility = JavaVersion.VERSION_1_8
    targetCompatibility = JavaVersion.VERSION_1_8
}

android {
    namespace = "org.matilda"
    compileSdk = 36

    compileOptions.apply {
        sourceCompatibility = JavaVersion.VERSION_1_8
        targetCompatibility = JavaVersion.VERSION_1_8
    }
}

val protobufVersion: String by project
val pbandkVersion: String by project
val kotlinInjectVersion: String by project
val daggerVersion: String by project

kotlin {
    jvm()
    androidTarget()

    linuxX64 {
        val main by compilations.getting
        val interop by main.cinterops.creating {
            packageName("org.matilda.plugins.interop")
        }
    }

    androidNativeArm32 {
        val main by compilations.getting
        val interop by main.cinterops.creating {
            packageName("org.matilda.plugins.interop")
        }
    }

    androidNativeArm64 {
        val main by compilations.getting
        val interop by main.cinterops.creating {
            packageName("org.matilda.plugins.interop")
        }
    }

    applyDefaultHierarchyTemplate()

    sourceSets {
        commonMain {
            dependencies {
                implementation("me.tatarka.inject:kotlin-inject-runtime:$kotlinInjectVersion")
                implementation("com.google.dagger:dagger:$daggerVersion")
                api("pro.streem.pbandk:pbandk-runtime:$pbandkVersion")
                api("com.google.protobuf:protobuf-kotlin:$protobufVersion")
                implementation("org.jetbrains.kotlinx:kotlinx-datetime:0.6.1")
                api(project(":commands-generator-api-common"))
            }
        }

        val javaMain by creating {
            dependsOn(commonMain.get())

            dependencies {
                api(project(":commands-generator-api-java"))
            }
        }

        jvmMain.get().dependsOn(javaMain)
        androidMain.get().dependsOn(javaMain)

        jvmTest {
            dependencies {
                implementation(project.dependencies.platform("org.junit:junit-bom:5.9.1"))
                implementation("org.junit.jupiter:junit-jupiter")
            }
        }
    }
}

dependencies {
    ksp("com.google.dagger:dagger-compiler:$daggerVersion")
    ksp("me.tatarka.inject:kotlin-inject-compiler-ksp:$kotlinInjectVersion")
    protobuf(project(":commands-generator-protos"))
    compileOnly("com.google.protobuf:protobuf-kotlin:$protobufVersion")
}

val pythonRootDir = rootProject.layout.projectDirectory.dir(providers.gradleProperty("PYTHON_ROOT_DIR_PATH")).get()

protobuf {
    protoc {
        // The artifact spec for the Protobuf Compiler
        artifact = "com.google.protobuf:protoc:$protobufVersion"
    }

    plugins {
        create("pbandk") {
            artifact = "pro.streem.pbandk:protoc-gen-pbandk-jvm:$pbandkVersion:jvm8@jar"
        }
    }

    generateProtoTasks {
        // Only generate sources for debug, to prevent non-flavored from having duplicated sources
        ofBuildType("debug").matching { !it.isTestVariant }.forEach { task ->
            task.builtins {
                create("python") {
                    task.doLast {
                        copy {
                            from(task.getOutputDir(this@create))
                            into(pythonRootDir)
                        }
                    }
                }

                findByName("java")?.also {
                    remove(it)
                }
            }
            task.plugins {
                create("pbandk") {
                    // Publish the code generated by pbandk as part of the current Kotlin Multiplatform project's
                    // `commonMain` source set. This allows other Kotlin Multiplatform sub-projects to consume the
                    // pbandk-generated Kotlin code using a regular gradle project dependency.
                    val outputDir = task.getOutputDir(this)
                    project.kotlin.sourceSets.commonMain.configure {
                        // `builtBy` ensures that gradle will automatically run the `generateProto` task before trying
                        // to compile the generated Kotlin code
                        kotlin.srcDir(project.files(outputDir).builtBy(task))
                    }
                }
            }
        }
    }
}

publishing {
    repositories {
        mavenLocal()
    }
}

tasks.withType<KotlinCompile>().configureEach {
    compilerOptions.jvmTarget.set(JvmTarget.JVM_1_8)
}