PYTHON_ROOT_DIR_PATH=..
PYTHON_GENERATED_PACKAGE=matilda.generated

RESOURCES_SUBDIR=matilda/resources

VERSION=0.8.0

kspVersion=2.0.21-1.0.25
kotlinVersion=2.0.21
protobufVersion=4.28.3
protobufPluginVersion=0.9.4
pbandkVersion=0.14.3
kotlinInjectVersion=0.7.2
androidPluginVersion=8.11.1

android.useAndroidX=true
kotlin.mpp.enableCInteropCommonization=true